-- Seed dữ liệu sách thật cho bảng `sach`
BEGIN TRANSACTION;
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Đắc Nhân Tâm', 'Dale Carnegie', 'Kỹ năng sống', 1936, 12);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Quẳng Gánh Lo Đi Và Vui Sống', 'Dale Carnegie', 'Kỹ năng sống', 1948, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nhà Giả Kim', 'Paulo Coelho', 'Văn học nước ngoài', 1988, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('7 Thói Quen Của Bạn Trẻ Thành Đạt', 'Sean Covey', 'Kỹ năng sống', 1998, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Đi Tìm Lẽ Sống', 'Viktor Frankl', 'Tâm lý học', 1946, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tôi Tài Giỏi, Bạn Cũng Thế', 'Adam Khoo', 'Kỹ năng sống', 1998, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Sức Mạnh Của Thói Quen', 'Charles Duhigg', 'Kỹ năng sống', 2012, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Dám Bị Ghét', 'Kishimi Ichiro & Koga Fumitake', 'Tâm lý học', 2013, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Hiểu Về Trái Tim', 'Minh Niệm', 'Kỹ năng sống', 2013, 11);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tuổi Trẻ Đáng Giá Bao Nhiêu', 'Rosie Nguyễn', 'Kỹ năng sống', 2016, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Cà Phê Cùng Tony', 'Tony Buổi Sáng', 'Kỹ năng sống', 2014, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Muôn Kiếp Nhân Sinh', 'Nguyên Phong', 'Tâm lý học', 2020, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tôi Tự Học', 'Nguyễn Duy Cần', 'Kỹ năng sống', 1954, 4);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Deep Work - Làm Ra Làm, Chơi Ra Chơi', 'Cal Newport', 'Kỹ năng sống', 2016, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tuần Làm Việc 4 Giờ', 'Tim Ferriss', 'Kỹ năng sống', 2007, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Đọc Vị Bất Kỳ Ai', 'David J. Lieberman', 'Kỹ năng sống', 2000, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Cha Giàu Cha Nghèo', 'Robert Kiyosaki', 'Kinh doanh', 1997, 14);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nghĩ Giàu Làm Giàu', 'Napoleon Hill', 'Kinh doanh', 1937, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Người Giàu Có Nhất Thành Babylon', 'George S. Clason', 'Kinh doanh', 1926, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Bí Mật Tư Duy Triệu Phú', 'T. Harv Eker', 'Kinh doanh', 2005, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Từ Tốt Đến Vĩ Đại', 'Jim Collins', 'Kinh doanh', 2001, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Khởi Nghiệp Tinh Gọn', 'Eric Ries', 'Kinh doanh', 2011, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nghệ Thuật Đàm Phán', 'Roger Fisher', 'Kinh doanh', 1981, 4);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Số Đỏ', 'Vũ Trọng Phụng', 'Văn học Việt Nam', 1936, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Chí Phèo', 'Nam Cao', 'Văn học Việt Nam', 1941, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Dế Mèn Phiêu Lưu Ký', 'Tô Hoài', 'Văn học Việt Nam', 1941, 12);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tắt Đèn', 'Ngô Tất Tố', 'Văn học Việt Nam', 1937, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Truyện Kiều', 'Nguyễn Du', 'Văn học Việt Nam', 1820, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Mắt Biếc', 'Nguyễn Nhật Ánh', 'Văn học Việt Nam', 1990, 11);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Cho Tôi Xin Một Vé Đi Tuổi Thơ', 'Nguyễn Nhật Ánh', 'Văn học Việt Nam', 2008, 13);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tôi Thấy Hoa Vàng Trên Cỏ Xanh', 'Nguyễn Nhật Ánh', 'Văn học Việt Nam', 2010, 12);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Kính Vạn Hoa', 'Nguyễn Nhật Ánh', 'Văn học Việt Nam', 1995, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nhật Ký Đặng Thùy Trâm', 'Đặng Thùy Trâm', 'Văn học Việt Nam', 2005, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nỗi Buồn Chiến Tranh', 'Bảo Ninh', 'Văn học Việt Nam', 1990, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Việt Nam Sử Lược', 'Trần Trọng Kim', 'Lịch sử', 1920, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nhà Thờ Đức Bà Paris', 'Victor Hugo', 'Văn học nước ngoài', 1831, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Những Người Khốn Khổ', 'Victor Hugo', 'Văn học nước ngoài', 1862, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Ông Già Và Biển Cả', 'Ernest Hemingway', 'Văn học nước ngoài', 1952, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Trăm Năm Cô Đơn', 'Gabriel García Márquez', 'Văn học nước ngoài', 1967, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Hoàng Tử Bé', 'Antoine de Saint-Exupéry', 'Văn học nước ngoài', 1943, 14);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Chiến Tranh Và Hòa Bình', 'Lev Tolstoy', 'Văn học nước ngoài', 1869, 4);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tội Ác Và Trừng Phạt', 'Fyodor Dostoevsky', 'Văn học nước ngoài', 1866, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Anh Em Nhà Karamazov', 'Fyodor Dostoevsky', 'Văn học nước ngoài', 1880, 4);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Rừng Na Uy', 'Haruki Murakami', 'Văn học nước ngoài', 1987, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Biên Niên Ký Chim Vặn Dây Cót', 'Haruki Murakami', 'Văn học nước ngoài', 1994, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('1984', 'George Orwell', 'Văn học nước ngoài', 1949, 11);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Trại Súc Vật', 'George Orwell', 'Văn học nước ngoài', 1945, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Giết Con Chim Nhại', 'Harper Lee', 'Văn học nước ngoài', 1960, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Bố Già', 'Mario Puzo', 'Văn học nước ngoài', 1969, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Kiêu Hãnh Và Định Kiến', 'Jane Austen', 'Văn học nước ngoài', 1813, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Người Đua Diều', 'Khaled Hosseini', 'Văn học nước ngoài', 2003, 10);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nghìn Mặt Trời Rực Rỡ', 'Khaled Hosseini', 'Văn học nước ngoài', 2007, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya', 'Higashino Keigo', 'Văn học nước ngoài', 2012, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Bạch Dạ Hành', 'Higashino Keigo', 'Trinh thám', 1999, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Sherlock Holmes Toàn Tập', 'Arthur Conan Doyle', 'Trinh thám', 1892, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Mười Người Da Đen Nhỏ', 'Agatha Christie', 'Trinh thám', 1939, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Vụ Án Mạng Trên Chuyến Tàu Tốc Hành Phương Đông', 'Agatha Christie', 'Trinh thám', 1934, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Mật Mã Da Vinci', 'Dan Brown', 'Trinh thám', 2003, 12);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Thiên Thần Và Ác Quỷ', 'Dan Brown', 'Trinh thám', 2000, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tâm Lý Học Đám Đông', 'Gustave Le Bon', 'Tâm lý học', 1895, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Tư Duy Nhanh Và Chậm', 'Daniel Kahneman', 'Tâm lý học', 2011, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Trí Tuệ Xúc Cảm', 'Daniel Goleman', 'Tâm lý học', 1995, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Sapiens: Lược Sử Loài Người', 'Yuval Noah Harari', 'Khoa học', 2011, 13);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Homo Deus: Lược Sử Tương Lai', 'Yuval Noah Harari', 'Khoa học', 2015, 9);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Lược Sử Thời Gian', 'Stephen Hawking', 'Khoa học', 1988, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Vũ Trụ Trong Vỏ Hạt Dẻ', 'Stephen Hawking', 'Khoa học', 2001, 5);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Súng, Vi Trùng Và Thép', 'Jared Diamond', 'Khoa học', 1997, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Không Gia Đình', 'Hector Malot', 'Thiếu nhi', 1878, 7);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Peter Pan', 'J. M. Barrie', 'Thiếu nhi', 1911, 6);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Alice Ở Xứ Sở Thần Tiên', 'Lewis Carroll', 'Thiếu nhi', 1865, 8);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Harry Potter Và Hòn Đá Phù Thủy', 'J. K. Rowling', 'Thiếu nhi', 1997, 15);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Harry Potter Và Phòng Chứa Bí Mật', 'J. K. Rowling', 'Thiếu nhi', 1998, 14);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Harry Potter Và Tên Tù Nhân Ngục Azkaban', 'J. K. Rowling', 'Thiếu nhi', 1999, 13);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Harry Potter Và Chiếc Cốc Lửa', 'J. K. Rowling', 'Thiếu nhi', 2000, 12);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Doraemon', 'Fujiko F. Fujio', 'Truyện tranh', 1969, 20);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Thám Tử Lừng Danh Conan', 'Gosho Aoyama', 'Truyện tranh', 1994, 18);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Naruto', 'Masashi Kishimoto', 'Truyện tranh', 1999, 16);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('One Piece', 'Eiichiro Oda', 'Truyện tranh', 1997, 20);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Bảy Viên Ngọc Rồng', 'Akira Toriyama', 'Truyện tranh', 1984, 15);
INSERT INTO sach (ten_sach, tac_gia, the_loai, nam_xuat_ban, so_luong) VALUES ('Nhóc Miko', 'Hiroyuki Egami & Ema Toyama', 'Truyện tranh', 2003, 9);
COMMIT;
